application: the-tasty-samosa
version: web-dev
runtime: python27
api_version: 1
threadsafe: true

builtins:
- remote_api: on

handlers:
- url: /js
  static_dir: public/
- url: /css
  static_dir: public/
- url: /
  static_files: public/index.html
  upload: public/index\.html
- url: /
  static_dir: public/

