application: the-tasty-samosa
version: web-dev
runtime: python27
api_version: 1
threadsafe: true

builtins:
- remote_api: on

handlers:
- url: /
  static_files: index.html
  upload: index\.html
- url: /node_modules/react/dist/react-with-addons.js
  static_files: node_modules/react/dist/react-with-addons.js
  upload: node_modules/react/dist/react-with-addons\.js
- url: /bundle.js
  static_files: bundle.js
  upload: bundle\.js
- url: /public/images
  static_dir: public/images
- url: /.*
  static_files: index.html
  upload: index\.html
